### ISSUE TITLE
Enable tab duplication

### ISSUE THREAD

**Issue by barisicm** [serenadeai/chrome#11]
While using chrome, i find it usefull to be able to duplicate tabs.

**Comment by kyle-wilson** [comment]
Obviously, Serenade does not support this natively. The best solution in my opinion is to rely on keyboard shortcuts and use a custom command. To my knowledge, Chrome does not offer a keyboard shortcut for duplicate tab. Therefore, I believe the best course of action is to use a chrome extension [like this one](https://chrome.google.com/webstore/detail/duplicate-tab-shortcut/klehggjefofgiajjfpoebdidnpjmljhb?hl=en#:~:text=Duplicate%20Tab%20Shortcut&text=Press%20Alt%2BShift%2BD%20to,Shift%2BD%20on%20Mac). Then write a custom command and place it in `.serenade/scripts/custom.js`:
```
serenade.app("chrome").command("duplicate tab", async (api) => {
  await api.pressKey("d", ["option", "shift"]);
});
```

**Comment by ummcheng** [comment]
@barisicm, @kyle-wilson Thanks for the ideas! We've just added native support for this at the API level with https://github.com/serenadeai/chrome/commit/04dd57d92fce6a76eeaaf8d8707967cda14184c8, and this should be reaching the Chrome Web Store and the Serenade app in the next week or so!
